/**
 * The RESOLVED schedule: what the run intended to offer, and for how long,
 * stated in the units a reader (and tools/correlate_run.py) actually needs.
 *
 * Why this exists at all: `resolved_config` publishes the shape NAME and the
 * anchor, and `rate` publishes the PEAK stage only. Neither says how long
 * each stage lasts or what any non-peak stage offered, so anyone reading a
 * timeline had to re-derive the stage boundaries from the delivered EPS — a
 * heuristic that mislabels every stage of a run that failed to keep up,
 * which is precisely the run worth analysing. This block states the intent
 * that the delivered numbers should be read against.
 *
 * Derived from the k6 scenario object src/scenarios/resolve.ts already
 * produces, not recomputed from the shape: whatever k6 was actually handed
 * is what this describes, rounding and all.
 */

/** One resolved stage. `target` is what k6 was told; the eps figure is what
 * that means for the whole fleet at that stage. */
export interface ScheduleStage {
  /** k6's own `target`: ITERATIONS per second, per generator. */
  target_iterations_per_sec: number;
  /** target_iterations_per_sec * batch_size * gen_count — events per second
   * offered by the WHOLE fleet at this stage, comparable with a timeline
   * bucket's `eps` (which is also fleet-wide on a merged timeline). */
  target_eps_fleet: number;
  /** The stage's length in seconds, AFTER DURATION_SCALE. */
  duration_sec: number;
}

export interface TypeSchedule {
  executor: string;
  duration_scale: number;
  gen_count: number;
  batch_size: number;
  /** ramping-arrival-rate only: k6's `startRate`, iterations/s per generator. */
  start_rate_per_sec?: number;
  /** shared-iterations only. */
  iterations?: number;
  /** shared-iterations only. */
  vus?: number;
  /** In order. Empty for a shared-iterations shape, which has no stages. */
  stages: ScheduleStage[];
}

/** One entry per ACTIVE type, keyed by type name — stages are per type. */
export type RunSchedule = Record<string, TypeSchedule>;

export interface ScheduleContext {
  batch_size: number;
  gen_count: number;
  duration_scale: number;
}

const DURATION_UNITS: Record<string, number> = { h: 3600, m: 60, s: 1, ms: 0.001 };
const DURATION_PART = /(\d+(?:\.\d+)?)(ms|h|m|s)/g;

/**
 * k6 duration string -> seconds. resolveScenario only ever emits `"<n>s"`,
 * but k6's own grammar allows `1m30s`, so parse the general form.
 *
 * Throws rather than returning a fallback: every value reaching here was
 * generated by this codebase, so an unparseable one is an internal
 * invariant violation, and a silent 0 would publish a schedule whose stage
 * boundaries are all at the same instant — worse than a loud failure.
 */
export function parseK6DurationSec(d: string): number {
  DURATION_PART.lastIndex = 0;
  let total = 0;
  let matched = 0;
  let m: RegExpExecArray | null;
  while ((m = DURATION_PART.exec(d)) !== null) {
    total += Number(m[1]) * DURATION_UNITS[m[2]];
    matched += m[0].length;
  }
  if (matched !== d.length || d.length === 0) {
    throw new Error(`could not read k6 duration ${JSON.stringify(d)} as a number of seconds`);
  }
  return total;
}

interface K6Stage {
  target?: unknown;
  duration?: unknown;
}

/**
 * The resolved schedule for ONE type, from that type's k6 scenario object
 * (see ResolvedScenario.k6) and the context that produced it.
 */
export function scheduleForType(k6: Record<string, unknown>, ctx: ScheduleContext): TypeSchedule {
  const executor = typeof k6.executor === 'string' ? k6.executor : 'unknown';
  const base: TypeSchedule = {
    executor,
    duration_scale: ctx.duration_scale,
    gen_count: ctx.gen_count,
    batch_size: ctx.batch_size,
    stages: [],
  };

  if (executor === 'shared-iterations') {
    if (typeof k6.iterations === 'number') base.iterations = k6.iterations;
    if (typeof k6.vus === 'number') base.vus = k6.vus;
    return base;
  }

  if (typeof k6.startRate === 'number') base.start_rate_per_sec = k6.startRate;
  const raw = Array.isArray(k6.stages) ? (k6.stages as K6Stage[]) : [];
  base.stages = raw.map((s) => {
    const target = typeof s.target === 'number' ? s.target : 0;
    return {
      target_iterations_per_sec: target,
      target_eps_fleet: target * ctx.batch_size * ctx.gen_count,
      duration_sec: parseK6DurationSec(String(s.duration)),
    };
  });
  return base;
}
